### ISSUE TITLE
HTTPS server fail to handle request

### ISSUE THREAD

**Issue by kfyharukz** [cybozu-go/well#27]
HTTPS server cannot handle http request with `well` with cods:
```golang
serv := &well.HTTPServer{
		Server: &http.Server{
			Addr:    config.listenAddr,
			Handler: h,
		},
	}

err = serv.ListenAndServeTLS("server.crt", "server.key")
```
Error is as below:
```
2019-05-21T02:43:15.273506Z kaz-ubuntu topolvm-hook info: "http2: panic serving 127.0.0.1:58100: interface conversion: *http.http2responseWriter is not well.StdResponseWriter: missing method Hijack"
2019-05-21T02:43:15.275443Z kaz-ubuntu topolvm-hook info: "goroutine 9 [running]:"
2019-05-21T02:43:15.275449Z kaz-ubuntu topolvm-hook info: "net/http.(*http2serverConn).runHandler.func1(0xc00000e5b8, 0xc0000b4faf, 0xc0002d4a80)"
2019-05-21T02:43:15.275452Z kaz-ubuntu topolvm-hook info: "\t/usr/local/go/src/net/http/h2_bundle.go:5651 +0x16b"
2019-05-21T02:43:15.275454Z kaz-ubuntu topolvm-hook info: "panic(0x1152ba0, 0xc0002bc450)"
2019-05-21T02:43:15.275456Z kaz-ubuntu topolvm-hook info: "\t/usr/local/go/src/runtime/panic.go:522 +0x1b5"
2019-05-21T02:43:15.275460Z kaz-ubuntu topolvm-hook info: "github.com/cybozu-go/well.(*HTTPServer).ServeHTTP(0xc00036c000, 0x144da40, 0xc00000e5b8, 0xc0001a4700)"
2019-05-21T02:43:15.275463Z kaz-ubuntu topolvm-hook info: "\t/home/kazuhito/go/src/github.com/cybozu-go/topolvm/vendor/github.com/cybozu-go/well/http.go:119 +0x7e"
2019-05-21T02:43:15.275466Z kaz-ubuntu topolvm-hook info: "net/http.serverHandler.ServeHTTP(0xc000362410, 0x144da40, 0xc00000e5b8, 0xc0001a4700)"
2019-05-21T02:43:15.275468Z kaz-ubuntu topolvm-hook info: "\t/usr/local/go/src/net/http/server.go:2774 +0xa8"
2019-05-21T02:43:15.275471Z kaz-ubuntu topolvm-hook info: "net/http.initNPNRequest.ServeHTTP(0xc000086a80, 0xc000362410, 0x144da40, 0xc00000e5b8, 0xc0001a4700)"
2019-05-21T02:43:15.275474Z kaz-ubuntu topolvm-hook info: "\t/usr/local/go/src/net/http/server.go:3323 +0x8d"
2019-05-21T02:43:15.275476Z kaz-ubuntu topolvm-hook info: "net/http.(*http2serverConn).runHandler(0xc0002d4a80, 0xc00000e5b8, 0xc0001a4700, 0xc0001f8740)"
2019-05-21T02:43:15.275479Z kaz-ubuntu topolvm-hook info: "\t/usr/local/go/src/net/http/h2_bundle.go:5658 +0x89"
2019-05-21T02:43:15.275481Z kaz-ubuntu topolvm-hook info: "created by net/http.(*http2serverConn).processHeaders"
2019-05-21T02:43:15.275483Z kaz-ubuntu topolvm-hook info: "\t/usr/local/go/src/net/http/h2_bundle.go:5392 +0x4f4"
2019-05-21T02:43:25.942018Z kaz-ubuntu topolvm-hook info: "http2: panic serving 127.0.0.1:58218: interface conversion: *http.http2responseWriter is not well.StdResponseWriter: missing method Hijack"
2019-05-21T02:43:25.942081Z kaz-ubuntu topolvm-hook info: "goroutine 25 [running]:"
2019-05-21T02:43:25.942084Z kaz-ubuntu topolvm-hook info: "net/http.(*http2serverConn).runHandler.func1(0xc0002f8000, 0xc00034dfaf, 0xc000231380)"
2019-05-21T02:43:25.942087Z kaz-ubuntu topolvm-hook info: "\t/usr/local/go/src/net/http/h2_bundle.go:5651 +0x16b"
2019-05-21T02:43:25.942090Z kaz-ubuntu topolvm-hook info: "panic(0x1152ba0, 0xc0001620c0)"
2019-05-21T02:43:25.942092Z kaz-ubuntu topolvm-hook info: "\t/usr/local/go/src/runtime/panic.go:522 +0x1b5"
2019-05-21T02:43:25.942094Z kaz-ubuntu topolvm-hook info: "github.com/cybozu-go/well.(*HTTPServer).ServeHTTP(0xc00036c000, 0x144da40, 0xc0002f8000, 0xc0001a4600)"
2019-05-21T02:43:25.942097Z kaz-ubuntu topolvm-hook info: "\t/home/kazuhito/go/src/github.com/cybozu-go/topolvm/vendor/github.com/cybozu-go/well/http.go:119 +0x7e"
2019-05-21T02:43:25.942100Z kaz-ubuntu topolvm-hook info: "net/http.serverHandler.ServeHTTP(0xc000362410, 0x144da40, 0xc0002f8000, 0xc0001a4600)"
2019-05-21T02:43:25.942102Z kaz-ubuntu topolvm-hook info: "\t/usr/local/go/src/net/http/server.go:2774 +0xa8"
2019-05-21T02:43:25.942105Z kaz-ubuntu topolvm-hook info: "net/http.initNPNRequest.ServeHTTP(0xc000160380, 0xc000362410, 0x144da40, 0xc0002f8000, 0xc0001a4600)"
2019-05-21T02:43:25.942107Z kaz-ubuntu topolvm-hook info: "\t/usr/local/go/src/net/http/server.go:3323 +0x8d"
2019-05-21T02:43:25.942109Z kaz-ubuntu topolvm-hook info: "net/http.(*http2serverConn).runHandler(0xc000231380, 0xc0002f8000, 0xc0001a4600, 0xc00030e260)"
2019-05-21T02:43:25.942112Z kaz-ubuntu topolvm-hook info: "\t/usr/local/go/src/net/http/h2_bundle.go:5658 +0x89"
2019-05-21T02:43:25.942114Z kaz-ubuntu topolvm-hook info: "created by net/http.(*http2serverConn).processHeaders"
2019-05-21T02:43:25.942117Z kaz-ubuntu topolvm-hook info: "\t/usr/local/go/src/net/http/h2_bundle.go:5392 +0x4f4"
2019-05-21T02:43:34.493591Z kaz-ubuntu topolvm-hook warning: "well: got signal" signal="terminated"
```

**Comment by Hsn723** [comment]
Thank you for your report. It seems that when using HTTP/2 the `http.ResponseWriter` instance that gets passed (`*http.http2responseWriter`) does not implement all the methods that `http.response` does for HTTP 1.1.

At the moment, as a workaround, if this is acceptable in your environment I would suggest making requests via HTTP 1.1, or running your server program with `GODEBUG=http2server=0` while we look further into it.

**Comment by ymmt2005** [comment]
I have investigated HTTP/2 implementation in Go 1.11, 1.12. 1.13.

- All implement `http.Pusher` interface, as PUSH is only for HTTP/2.
    - https://github.com/golang/go/blob/dev.boringcrypto.go1.11/src/net/http/h2_bundle.go#L3060
- All implement `http.CloseNotifier`, `http.Flusher`, and `io.StringWriter`:
    - https://github.com/golang/go/blob/dev.boringcrypto.go1.11/src/net/http/h2_bundle.go#L6084
    - https://github.com/golang/go/blob/dev.boringcrypto.go1.12/src/net/http/h2_bundle.go#L5865
    - https://github.com/golang/go/blob/dev.boringcrypto.go1.13/src/net/http/h2_bundle.go#L5890
- None implements `io.ReaderFrom`.
- None implements `http.Hijacker`.

[`well.StdResponseWriter`](https://github.com/cybozu-go/well/blob/aeb2080eb80be3e842ac9db768cf19d949f7965c/http.go#L73) interface is intended to provide as much capabilities of the underlying `http.ResponseWriter` as possible.

As the proposed fix in #28 conceals the capabilities of the underlying `http.ResponseWriter`,
I would like to explore alternative ways.

**Comment by ymmt2005** [comment]
@Hsn723 
I'd like to propose #32.  Could you please take a look?

**Comment by Hsn723** [comment]
@ymmt2005 Looks good to me, I added some comments concerning style.
